# Generated by Django 1.11.16 on 2018-10-25 09:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("payments", "0003_auto_20181024_1604")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        )
    ]
