# Generated by Django 1.11.16 on 2018-11-01 08:00

import vies.models
import vies.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("payments", "0005_auto_20181025_1135")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Postcode and city"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=vies.models.VATINField(
                blank=True,
                help_text=(
                    "Please fill in European Union VAT ID, "
                    "leave blank if not applicable."
                ),
                max_length=14,
                null=True,
                validators=[vies.validators.VATINValidator(validate=True, verify=True)],
                verbose_name="European VAT ID",
            ),
        ),
    ]
