# Generated by Django 2.0.7 on 2018-11-27 13:07

import weblate.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0009_auto_20181113_2339")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="backend",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="details",
            field=weblate.utils.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name="payment",
            name="extra",
            field=weblate.utils.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name="payment",
            name="recurring",
            field=models.CharField(
                blank=True,
                choices=[("y", "Yearly"), ("m", "Monthly"), ("", "None")],
                default="",
                max_length=10,
            ),
        ),
    ]
