# Generated by Django 3.0.4 on 2020-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0014_auto_20200316_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.IntegerField(
                choices=[(0, "EUR"), (1, "BTC"), (2, "USD"), (3, "CZK")], default=0
            ),
        ),
    ]
