# Generated by Django 3.0.8 on 2020-08-21 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0017_auto_20200422_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payments.Customer"
            ),
        ),
    ]
