# Generated by Django 3.2.12 on 2022-09-15 11:01

from django.db import migrations
from weblate.utils.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_auto_20200821_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="details",
            field=JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="extra",
            field=JSONField(blank=True, default=dict),
        ),
    ]
