# Generated by Django 3.2.11 on 2022-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_auto_20220915_1301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="recurring",
            field=models.CharField(
                blank=True,
                choices=[
                    ("y", "Annual"),
                    ("b", "Biannual"),
                    ("q", "Quarterly"),
                    ("m", "Monthly"),
                    ("", "One-time"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
