# Generated by Django 4.2.2 on 2023-08-08 11:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0020_alter_payment_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="details_new",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="extra_new",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
