# Generated by Django 4.2.2 on 2023-08-08 11:12

from django.db import migrations


def jsonfield(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model = apps.get_model("payments", "Payment")
    fields = (
        ("details", "details_new"),
        ("extra", "extra_new"),
    )

    updates = []
    for obj in model.objects.using(db_alias).iterator():
        for field, new_field in fields:
            setattr(obj, new_field, getattr(obj, field))
        updates.append(obj)
        if len(updates) > 1000:
            model.objects.using(db_alias).bulk_update(
                updates, ["details_new", "extra_new"]
            )
            updates = []

    if updates:
        model.objects.using(db_alias).bulk_update(updates, ["details_new", "extra_new"])
        updates = []


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0021_payment_details_new_payment_extra_new"),
    ]

    operations = [migrations.RunPython(jsonfield, elidable=True)]
