# Generated by Django 4.2.2 on 2023-08-08 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0023_remove_payment_details_remove_payment_extra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="details_new",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="extra_new",
            new_name="extra",
        ),
    ]
