# Generated by Django 5.0.6 on 2024-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0026_customer_address_2_customer_postcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
