# Generated by Django 5.1.2 on 2024-11-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0037_alter_customer_vat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.IntegerField(
                        choices=[(1, "Data Processing Agreement")], default=1
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.customer",
                    ),
                ),
            ],
        ),
    ]
