server {
    listen 80;
    listen [::]:80;
    server_name md.weblate.org;

    return 301 https://md.weblate.org$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name md.weblate.org;

    ssl_certificate /etc/ssl/md.weblate.org/current/fullchain.pem;
    ssl_certificate_key /etc/ssl/md.weblate.org/current/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /srv/website/mail-server;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        try_files $uri =404;
    }

    # This directory also contains deployment scripts and configuration.
    location / {
        return 404;
    }
}
