# Generated by Django 5.1.3 on 2024-12-06 19:54

import uuid

import django.core.serializers.json
import django.db.models.deletion
import django_countries.fields
import vies.models
from django.conf import settings
from django.db import migrations, models

import weblate_web.payments.fields
import weblate_web.payments.utils
import weblate_web.payments.validators


class Migration(migrations.Migration):
    replaces = [
        ("payments", "0001_squashed_0024_rename_details_new_payment_details_and_more"),
        ("payments", "0025_alter_payment_uuid"),
        ("payments", "0026_customer_address_2_customer_postcode_and_more"),
        ("payments", "0027_payment_card_info"),
        ("payments", "0028_alter_customer_email"),
        ("payments", "0029_payment_paid_invoice"),
        ("payments", "0030_customer_discount"),
        ("payments", "0031_alter_payment_customer_alter_payment_paid_invoice_and_more"),
        ("payments", "0032_payment_draft_invoice_alter_payment_paid_invoice"),
        ("payments", "0033_alter_customer_address_alter_customer_address_2_and_more"),
        ("payments", "0034_remove_payment_draft_invoice_and_more"),
        ("payments", "0035_payment_draft_invoice_payment_paid_invoice"),
        ("payments", "0036_alter_payment_currency"),
        ("payments", "0037_alter_customer_vat"),
        ("payments", "0038_alter_customer_tax"),
        ("payments", "0039_customer_users"),
        ("payments", "0040_fill_in_users"),
    ]

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("invoices", "0002_alter_invoice_customer_alter_invoice_discount_and_more"),
        ("invoices", "0011_invoice_invoiceitem_invoice_unique_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat",
                    vies.models.VATINField(
                        blank=True,
                        default="",
                        help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                        max_length=14,
                        null=True,
                        validators=[weblate_web.payments.validators.validate_vatin],
                        verbose_name="European VAT ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Company or individual name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=200, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=200, verbose_name="City"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Additional e-mail to receive billing notifications",
                        max_length=190,
                        validators=[weblate_web.payments.utils.validate_email],
                        verbose_name="Billing e-mail",
                    ),
                ),
                ("origin", models.URLField(max_length=300)),
                ("user_id", models.IntegerField()),
                (
                    "tax",
                    models.CharField(
                        blank=True,
                        help_text="Please fill in your company registration number if it should appear on the invoice.",
                        max_length=200,
                        verbose_name="Company identification number",
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Additional address information",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        default="", max_length=20, verbose_name="Postcode"
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.discount",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uuid",
                    weblate_web.payments.fields.Char32UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "recurring",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("y", "Annual"),
                            ("b", "Biannual"),
                            ("q", "Quarterly"),
                            ("m", "Monthly"),
                            ("", "One-time"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("backend", models.CharField(blank=True, default="", max_length=100)),
                (
                    "repeat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.payment",
                    ),
                ),
                ("invoice", models.CharField(blank=True, default="", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.customer",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "New payment"),
                            (2, "Awaiting payment"),
                            (3, "Payment rejected"),
                            (4, "Payment accepted"),
                            (5, "Payment processed"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("amount_fixed", models.BooleanField(blank=True, default=False)),
                ("end", models.DateField(blank=True, null=True)),
                ("start", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.IntegerField(
                        choices=[
                            (0, "EUR"),
                            (1, "BTC"),
                            (2, "USD"),
                            (3, "CZK"),
                            (4, "GBP"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("card_info", models.JSONField(blank=True, default=dict)),
                (
                    "draft_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_payment_set",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "paid_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_payment_set",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
