#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import vies.models
from django.conf import settings
from django.db import migrations, models

import weblate_web.payments.utils
import weblate_web.payments.validators


class Migration(migrations.Migration):
    replaces = [
        ("payments", "0001_squashed_0024_rename_details_new_payment_details_and_more"),
    ]

    initial = True

    dependencies = [
        ("invoices", "0001_squashed_0025_invoice_quote_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "currency",
                    models.IntegerField(
                        choices=[
                            (0, "EUR"),
                            (1, "BTC"),
                            (2, "USD"),
                            (3, "CZK"),
                            (4, "GBP"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "recurring",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("y", "Annual"),
                            ("b", "Biannual"),
                            ("q", "Quarterly"),
                            ("m", "Monthly"),
                            ("", "One-time"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "New payment"),
                            (2, "Awaiting payment"),
                            (3, "Payment rejected"),
                            (4, "Payment accepted"),
                            (5, "Payment processed"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("backend", models.CharField(blank=True, default="", max_length=100)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("invoice", models.CharField(blank=True, default="", max_length=20)),
                ("amount_fixed", models.BooleanField(blank=True, default=False)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("card_info", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat",
                    vies.models.VATINField(
                        blank=True,
                        default="",
                        help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                        max_length=14,
                        null=True,
                        validators=[weblate_web.payments.validators.validate_vatin],
                        verbose_name="European VAT ID",
                    ),
                ),
                (
                    "vat_validated",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "vat_validation_state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unknown"), (1, "Valid"), (2, "Invalid")],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "vat_validation_error",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "tax",
                    models.CharField(
                        blank=True,
                        help_text="Please fill in your company registration number if it should appear on the invoice.",
                        max_length=200,
                        verbose_name="Company identification number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        default="",
                        help_text="Company or individual name as it should appear on the invoice.",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=200, verbose_name="Address"
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Additional address information",
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=200, verbose_name="City"),
                ),
                (
                    "postcode",
                    models.CharField(
                        default="", max_length=20, verbose_name="Postcode"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Additional e-mail to receive billing notifications",
                        max_length=190,
                        validators=[weblate_web.payments.utils.validate_email],
                        verbose_name="Billing e-mail",
                    ),
                ),
                (
                    "contact_point",
                    models.CharField(
                        blank=True,
                        help_text="Person, team, or department to show as the invoice contact.",
                        max_length=200,
                        verbose_name="Contact point",
                    ),
                ),
                (
                    "accounting_reference",
                    models.CharField(
                        blank=True,
                        help_text="Line-level accounting code for the customer's internal invoice processing, such as a cost center, project, internal order, or GL account. Separate from the customer reference or purchase order number.",
                        max_length=200,
                        verbose_name="Accounting reference",
                    ),
                ),
                (
                    "upcoming_payment_notification_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days before the payment due date to send one extra upcoming payment notification, from 0 to 90. Set to 0 to use only default notifications.",
                        validators=[django.core.validators.MaxValueValidator(90)],
                        verbose_name="Additional upcoming payment notification",
                    ),
                ),
                ("origin", models.URLField(max_length=300)),
                ("user_id", models.IntegerField()),
                (
                    "end_client",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="End client name",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("zammad_id", models.IntegerField(default=0, editable=False)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.discount",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerFollowUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_up_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date and time when this customer needs attention.",
                        verbose_name="Follow-up date",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Short description of the next action.",
                        max_length=200,
                        verbose_name="Follow-up note",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Manual"),
                            (2, "Duplicate payment"),
                            (3, "Locked site URL"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="Follow-up type",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="payments.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer follow-up",
                "verbose_name_plural": "Customer follow-ups",
                "ordering": ["follow_up_at"],
            },
        ),
    ]
