# Generated by Django 4.2.2 on 2023-09-18 11:36

import uuid

import django.core.serializers.json
import django.db.models.deletion
import django_countries.fields
import vies.models
from django.db import migrations, models

import weblate_web.payments.utils
import weblate_web.payments.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat",
                    vies.models.VATINField(
                        blank=True,
                        help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                        max_length=14,
                        null=True,
                        validators=[weblate_web.payments.validators.validate_vatin],
                        verbose_name="European VAT ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Company or individual name",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, null=True, verbose_name="Address"),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Postcode and city"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=190,
                        validators=[weblate_web.payments.utils.validate_email],
                    ),
                ),
                ("origin", models.URLField(max_length=300)),
                ("user_id", models.IntegerField()),
                (
                    "tax",
                    models.CharField(
                        blank=True,
                        help_text="Please fill in your tax registration if it should appear on the invoice.",
                        max_length=200,
                        verbose_name="Tax registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "recurring",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("y", "Annual"),
                            ("b", "Biannual"),
                            ("q", "Quarterly"),
                            ("m", "Monthly"),
                            ("", "One-time"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("backend", models.CharField(blank=True, default="", max_length=100)),
                (
                    "repeat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
                ("invoice", models.CharField(blank=True, default="", max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.customer",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "New payment"),
                            (2, "Awaiting payment"),
                            (3, "Payment rejected"),
                            (4, "Payment accepted"),
                            (5, "Payment processed"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("amount_fixed", models.BooleanField(blank=True, default=False)),
                ("end", models.DateField(blank=True, null=True)),
                ("start", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.IntegerField(
                        choices=[(0, "EUR"), (1, "BTC"), (2, "USD"), (3, "CZK")],
                        default=0,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
