#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("payments", "0025_alter_payment_uuid"),
        ("payments", "0026_customer_address_2_customer_postcode_and_more"),
        ("payments", "0027_payment_card_info"),
        ("payments", "0028_alter_customer_email"),
        ("payments", "0029_payment_paid_invoice"),
        ("payments", "0030_customer_discount"),
        ("payments", "0031_alter_payment_customer_alter_payment_paid_invoice_and_more"),
        ("payments", "0032_payment_draft_invoice_alter_payment_paid_invoice"),
        ("payments", "0033_alter_customer_address_alter_customer_address_2_and_more"),
        ("payments", "0034_remove_payment_draft_invoice_and_more"),
        ("payments", "0035_payment_draft_invoice_payment_paid_invoice"),
        ("payments", "0036_alter_payment_currency"),
        ("payments", "0037_alter_customer_vat"),
        ("payments", "0038_alter_customer_tax"),
        ("payments", "0039_customer_users"),
        ("payments", "0040_fill_in_users"),
        ("payments", "0041_customer_created"),
        ("payments", "0042_alter_customer_name"),
        ("payments", "0043_fill_in_invoice"),
        ("payments", "0044_customer_end_client_customer_note_and_more"),
        ("payments", "0045_alter_customer_end_client"),
        ("payments", "0046_customer_zammad_id"),
        ("payments", "0047_payment_new_uuid"),
        ("payments", "0048_fill_in_uuid"),
        ("payments", "0049_alter_payment_new_uuid_alter_payment_uuid"),
        ("payments", "0050_remove_payment_uuid"),
        ("payments", "0051_rename_new_uuid_payment_uuid"),
        ("payments", "0052_payment_repeat"),
        ("payments", "0053_migrate_parent"),
        ("payments", "0054_remove_payment_repeat_value"),
        ("payments", "0055_customer_vat_validated"),
        ("payments", "0056_alter_customer_name"),
        ("payments", "0057_customer_upcoming_payment_notification_days"),
        ("payments", "0058_customer_vat_validation_state_and_error"),
        ("payments", "0059_customer_accounting_reference_customer_contact_point"),
        ("payments", "0060_customer_follow_up"),
        ("payments", "0061_customer_followup"),
    ]

    initial = True

    dependencies = [
        ("invoices", "0002_initial"),
        ("payments", "0001_squashed_0061_customerfollowup"),
        ("weblate_web", "0001_squashed_0052_discoveryactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerfollowup",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followups",
                to="weblate_web.service",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.customer"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="draft_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draft_payment_set",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_payment_set",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerfollowup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False), ("type", 3)),
                fields=("service", "type"),
                name="unique_locked_site_url_followup_per_service",
            ),
        ),
    ]
