# Generated by Django 5.1.2 on 2024-10-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
        ("payments", "0028_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.invoice",
            ),
        ),
    ]
