# Generated by Django 5.1.2 on 2024-10-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
        ("payments", "0029_payment_paid_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoices.discount",
            ),
        ),
    ]
