# Generated by Django 5.1.2 on 2024-10-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
        ("payments", "0030_customer_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.customer"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.payment",
            ),
        ),
    ]
