# Generated by Django 5.1.2 on 2024-10-22 09:11

import django_countries.fields
import vies.models
from django.db import migrations, models

import weblate_web.payments.validators


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0032_payment_draft_invoice_alter_payment_paid_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=200, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Additional address information",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(default="", max_length=200, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(
                default="", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Company or individual name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode",
            field=models.CharField(default="", max_length=20, verbose_name="Postcode"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=vies.models.VATINField(
                blank=True,
                default="",
                help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                max_length=14,
                validators=[weblate_web.payments.validators.validate_vatin],
                verbose_name="European VAT ID",
            ),
        ),
    ]
