# Generated by Django 5.1.7 on 2025-03-20 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0043_fill_in_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="end_client",
            field=models.CharField(
                default="", max_length=200, verbose_name="End client name"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
