# Generated by Django 5.1.7 on 2025-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0044_customer_end_client_customer_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="end_client",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="End client name"
            ),
        ),
    ]
