# Generated by Django 5.2.1 on 2025-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0045_alter_customer_end_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="zammad_id",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
