# Generated by Django 5.2.4 on 2025-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0046_customer_zammad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="new_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="repeat_value",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
