# Generated by Django 5.2.4 on 2025-07-28 09:20

from django.db import migrations

from weblate_web.payments.fields import migrate_uuid_field


def migrate(apps, schema_editor) -> None:
    migrate_uuid_field(apps.get_model("payments", "Payment"), "uuid", "new_uuid")
    migrate_uuid_field(
        apps.get_model("payments", "Payment"), "repeat_id", "repeat_value"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0047_payment_new_uuid"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True),
    ]
