# Generated by Django 5.2.4 on 2025-07-28 09:42

import uuid

from django.db import migrations, models

import weblate_web.payments.fields


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0048_fill_in_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="repeat",
        ),
        migrations.AlterField(
            model_name="payment",
            name="uuid",
            field=weblate_web.payments.fields.Char32UUIDField(
                default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="new_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
