# Generated by Django 5.2.4 on 2025-07-28 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0049_alter_payment_new_uuid_alter_payment_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="uuid",
        ),
    ]
