# Generated by Django 5.2.4 on 2025-07-28 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0050_remove_payment_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="new_uuid",
            new_name="uuid",
        ),
    ]
