# Generated by Django 5.2.4 on 2025-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0051_rename_new_uuid_payment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.payment",
            ),
        ),
    ]
