# Generated by Django 5.2.4 on 2025-07-28 10:24

from django.db import migrations

from weblate_web.payments.fields import migrate_uuid_field


def migrate(apps, schema_editor) -> None:
    # This is already UUID, but reuse the code
    migrate_uuid_field(
        apps.get_model("payments", "Payment"), "repeat_value", "repeat_id"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0052_payment_repeat"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True),
    ]
