# Generated by Django 5.2.4 on 2025-07-28 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0053_migrate_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="repeat_value",
        ),
    ]
