# Generated by Django 5.2.8 on 2025-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0054_remove_payment_repeat_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="vat_validated",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
