# Generated by Django 5.2.10 on 2026-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0055_customer_vat_validated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Company or individual name as it should appear on the invoice.",
                max_length=200,
                verbose_name="Name",
            ),
        ),
    ]
