# Generated by Django 5.2.12 on 2026-03-19 18:15

import django.core.validators
from django.db import migrations, models

from weblate_web.const import MAX_UPCOMING_PAYMENT_NOTIFICATION_DAYS


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0056_alter_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="upcoming_payment_notification_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text=f"Number of days before the payment due date to send one extra upcoming payment notification, from 0 to {MAX_UPCOMING_PAYMENT_NOTIFICATION_DAYS}. Set to 0 to use only default notifications.",
                validators=[
                    django.core.validators.MaxValueValidator(
                        MAX_UPCOMING_PAYMENT_NOTIFICATION_DAYS
                    )
                ],
                verbose_name="Additional upcoming payment notification",
            ),
        ),
    ]
