# Generated by Django 5.2.14 on 2026-05-20 00:00

import django.core.serializers.json
from django.db import migrations, models


def backfill_vat_validation_state(apps, schema_editor) -> None:
    customer = apps.get_model("payments", "Customer")
    customer.objects.filter(
        vat_validated__isnull=False,
        vat__isnull=False,
    ).exclude(vat="").update(
        vat_validation_state=1,
        vat_validation_error={},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0057_customer_upcoming_payment_notification_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="vat_validation_error",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_validation_state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Unknown"), (1, "Valid"), (2, "Invalid")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.RunPython(
            backfill_vat_validation_state, reverse_code=migrations.RunPython.noop
        ),
    ]
