#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.15 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0058_customer_vat_validation_state_and_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accounting_reference",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Line-level accounting code for the customer's internal invoice "
                    "processing, such as a cost center, project, internal order, or "
                    "GL account. Separate from the customer reference or purchase "
                    "order number."
                ),
                max_length=200,
                verbose_name="Accounting reference",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_point",
            field=models.CharField(
                blank=True,
                help_text="Person, team, or department to show as the invoice contact.",
                max_length=200,
                verbose_name="Contact point",
            ),
        ),
    ]
