#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.15 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0059_customer_accounting_reference_customer_contact_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="follow_up_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date and time when this customer needs attention.",
                null=True,
                verbose_name="Follow-up date",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="follow_up_note",
            field=models.CharField(
                blank=True,
                help_text="Short description of the next action.",
                max_length=200,
                verbose_name="Follow-up note",
            ),
        ),
    ]
