# Generated by Django 5.2.1 on 2025-05-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0045_alter_customer_end_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "origin",
                    models.IntegerField(
                        choices=[(1, "Outboud e-mail")], verbose_name="Origin"
                    ),
                ),
                ("summary", models.CharField(max_length=200, verbose_name="Summary")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "attachment",
                    models.FileField(
                        upload_to="crm/uploads/", verbose_name="Attachment"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="payments.customer",
                    ),
                ),
            ],
        ),
    ]
