#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import django.core.files.storage
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("CRM", "0001_initial"),
        ("CRM", "0002_alter_interaction_options_interaction_user_and_more"),
        ("CRM", "0003_alter_interaction_attachment"),
        ("CRM", "0004_interaction_remote_id_alter_interaction_origin_and_more"),
        ("CRM", "0005_alter_interaction_origin"),
        ("CRM", "0006_alter_interaction_origin"),
        ("CRM", "0007_alter_interaction_origin"),
        ("CRM", "0008_alter_interaction_origin"),
        ("CRM", "0009_interaction_details"),
        ("CRM", "0010_alter_interaction_origin"),
        ("CRM", "0011_delete_transient_vies_interactions"),
        ("CRM", "0012_alter_interaction_origin"),
    ]

    initial = True

    dependencies = [
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "origin",
                    models.IntegerField(
                        choices=[
                            (1, "Outbound e-mail"),
                            (2, "Merged customer"),
                            (3, "Attachment exchanged in Zammad"),
                            (4, "VIES validation"),
                            (5, "Manual payment"),
                            (6, "Maintenance window"),
                            (7, "Manual note"),
                            (8, "Quote status"),
                        ],
                        verbose_name="Origin",
                    ),
                ),
                ("summary", models.CharField(max_length=200, verbose_name="Summary")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=settings.CRM_ROOT
                        ),
                        upload_to="attachments",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "remote_id",
                    models.IntegerField(
                        default=0,
                        help_text="For example Zammad attachment ID",
                        verbose_name="Remote ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="payments.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ZammadSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                ("article_id", models.IntegerField(unique=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.customer",
                    ),
                ),
            ],
        ),
    ]
