# Generated by Django 5.2.1 on 2025-05-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaction",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="interaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="origin",
            field=models.IntegerField(
                choices=[(1, "Outboud e-mail"), (2, "Merged customer")],
                verbose_name="Origin",
            ),
        ),
    ]
