# Generated by Django 5.2.1 on 2025-05-29 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0003_alter_interaction_attachment"),
        ("payments", "0046_customer_zammad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="remote_id",
            field=models.IntegerField(
                default=0,
                help_text="For example Zammad attachment ID",
                verbose_name="Remote ID",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (1, "Outboud e-mail"),
                    (2, "Merged customer"),
                    (3, "Attachment exchanged in Zammad"),
                ],
                verbose_name="Origin",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
        migrations.CreateModel(
            name="ZammadSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                ("article_id", models.IntegerField(unique=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.customer",
                    ),
                ),
            ],
        ),
    ]
