# Generated by Django 5.2.4 on 2025-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0004_interaction_remote_id_alter_interaction_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (1, "Outbound e-mail"),
                    (2, "Merged customer"),
                    (3, "Attachment exchanged in Zammad"),
                ],
                verbose_name="Origin",
            ),
        ),
    ]
