# Generated by Django 5.2.13 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRM", "0006_alter_interaction_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (1, "Outbound e-mail"),
                    (2, "Merged customer"),
                    (3, "Attachment exchanged in Zammad"),
                    (4, "VIES validation"),
                    (5, "Manual payment"),
                ],
                verbose_name="Origin",
            ),
        ),
    ]
