#!/usr/bin/env python3
"""Simple script to accept all invitations on GitHub

It takes GitHub access token as single parameter.
"""
import sys

import requests


def main():
    headers = {
        "Content-Type": "application/json",
        "Authorization": "token {}".format(sys.argv[1]),
    }

    url = "https://api.github.com/user/memberships/orgs"
    accept_url = "https://api.github.com/user/memberships/orgs/{}"

    orgs = requests.get(url, headers=headers)
    orgs.raise_for_status()

    for org in orgs.json():
        if org["state"] == "pending":
            name = org["organization"]["login"]
            print("Accepting org {}".format(name))
            response = requests.patch(
                accept_url.format(name), '{"state":"active"}', headers=headers
            )
            response.raise_for_status()

    url = "https://api.github.com/user/repository_invitations"

    invitations = requests.get(url, headers=headers)
    invitations.raise_for_status()
    for invitation in invitations.json():
        print("Accepting {}".format(invitation["repository"]["html_url"]))
        response = requests.patch(
            "{}/{}".format(url, invitation["id"]), headers=headers
        )
        response.raise_for_status()


if __name__ == "__main__":
    main()
