#!/usr/bin/env python3
"""Simple script to accept all invitations on GitHub

It takes GitHub access token as single parameter.
"""
import sys
import requests


def main():
    headers = {
        "Content-Type": "application/json",
        "Authorization": "token {}".format(sys.argv[1]),
    }

    url = "https://api.github.com/user/repository_invitations"

    invitations = requests.get(url, headers=headers)
    invitations.raise_for_status()

    for invitation in invitations.json():
        print("Accepting {}".format(invitation["repository"]["html_url"]))
        response = requests.patch(
            "{}/{}".format(url, invitation["id"]), headers=headers
        )
        response.raise_for_status()


if __name__ == "__main__":
    main()
