#!/bin/sh

WEBLATE=~/weblate/weblate/docs/screenshots/
SCREENSHOTS=weblate_web/static/img/

convert $WEBLATE/screenshot-context.webp $SCREENSHOTS/BigScreenshot.png
convert $WEBLATE/checks.webp -crop 268x414+916+310 $SCREENSHOTS/dialog-checks.png
convert $WEBLATE/checks.webp -crop 268x704+916+929 $SCREENSHOTS/source-info.png
convert $WEBLATE/checks.webp -crop 800x435+20+1029 $SCREENSHOTS/comment-new.png
