#!/bin/sh

WEBLATE=~/weblate/weblate/docs/images/
SCREENSHOTS=weblate_web/static/img/

cp $WEBLATE/screenshot-context.png $SCREENSHOTS/BigScreenshot.png
convert $WEBLATE/checks.png -crop 276x148+946+235 $SCREENSHOTS/dialog-checks.png
convert $WEBLATE/checks.png -crop 276x453+946+621 $SCREENSHOTS/source-info.png
convert $WEBLATE/checks.png -crop 887x394+29+881 $SCREENSHOTS/comment-new.png
