#!/bin/sh

# Exit on failure
set -e

# Lock Weblate
wlc lock

# Push changes from Weblate to GitHub
wlc push

# Pull changes from GitHub
git pull --rebase

# Update po files itself
./manage.py makemessages -a --keep-pot -i 'weblate_web/files/*'

# Fix Report-Msgid-Bugs-To as it gets removed
sed -i 's/"Report-Msgid-Bugs-To:.*/"Report-Msgid-Bugs-To: weblate@lists.cihar.com\\n"/' locale/*/*/*.po locale/*.pot

# Commit changes
git add locale/*/*/*.po locale/django.pot
git commit -m "i18n: Update PO files"

# Push changes
git push

# Unlock Weblate
wlc unlock
