#!/bin/sh

# Exit on failure
set -e

# Lock Weblate
wlc lock

# Push changes from Weblate to GitHub
wlc commit

# Update Weblate remote
git remote update weblate

# Pull changes from GitHub
git rebase --onto weblate/main

# Cleanup locale dirs
find locale -name '*.mo' -o -name '*~' -delete
find locale -type d -empty -delete

# Update po files itself
./manage.py makemessages -a --keep-pot -i 'weblate_web/files/*'

# Fix Report-Msgid-Bugs-To as it gets removed
sed -i 's@"Report-Msgid-Bugs-To:.*@"Report-Msgid-Bugs-To: https://github.com/WeblateOrg/website/issues\\n"@' locale/*/*/*.po locale/*.pot

# Commit changes
git add locale/*/*/*.po locale/django.pot
git commit -m "i18n: Update PO files"

# Push changes
git push

# Unlock Weblate
wlc unlock
