#!/bin/sh

# Renerates .po files used for translating Weblate

# Exit on failure
set -e

export PYTHONPATH=../weblate
export DJANGO_SETTINGS_MODULE=wlhosted.settings_test

# Lock Weblate
wlc lock weblate/hosted

# Push changes from Weblate to GitHub
wlc push weblate/hosted

# Pull changes from GitHub
git pull --rebase

# Update po files itself
weblate makemessages --keep-pot -a -i 'data/*' -i 'docs/*' -i 'examples/*' -i 'build/*'

# Fix Report-Msgid-Bugs-To as it gets removed
sed \
    -i \
    -e 's/"Report-Msgid-Bugs-To:.*/"Report-Msgid-Bugs-To: weblate@lists.cihar.com\\n"/' \
    -e 's/"Project-Id-Version:.*/"Project-Id-Version: Hosted Weblate '$version'\\n"/' \
    wlhosted/locale/*/*/*.po wlhosted/locale/*.pot \

# Commit changes
git add wlhosted/locale/*/*/*.po
git add wlhosted/locale/*.pot

git commit -s -m "Update po files

[CI skip]"

# Push changes
git push

# Unlock Weblate
wlc unlock weblate/hosted
