#!/bin/sh
# Wrapper around yarn to update our javascript dependencies
set -e

cd scripts/yarn/

yarn install --check-files
if [ "$1" != "--no-upgrade" ] ; then
    yarn upgrade-interactive
fi

# Clipboard
cp node_modules/clipboard/dist/clipboard.min.js ../../weblate_web/static/vendor/clipboard.js

# Source Sans/Code Pro fonts
mkdir -p ../../weblate_web/static/font-source
sed '/font-family/ a font-display: swap;' < node_modules/source-sans/source-sans-3.css > ../../weblate_web/static/vendor/font-source/source-sans-3.css
sed '/font-family/ a font-display: swap;' < node_modules/source-code-pro/source-code-pro.css > ../../weblate_web/static/vendor/font-source/source-code-pro.css
find node_modules/source-sans/TTF node_modules/source-sans/WOFF2 node_modules/source-sans/WOFF node_modules/source-code-pro/ -name SourceSans3-ExtraLight.* -o  -name SourceSans3-Light.* -o  -name SourceSans3-Semibold.* -o -name SourceSans3-Black.* -o -name SourceSans3-Bold.* -o -name SourceSans3-Regular.* -o -name SourceSans3-It.* -o -name SourceSans3-BoldIt.* -o -name SourceCodePro-Medium.* -o -name SourceCodePro-Regular.* -o -name SourceCodePro-Bold.* -o -name SourceCodePro-Semibold.* | while read name ; do
    target=`echo $name | sed 's@node_modules/source-\(sans\|code-pro\)/@../../weblate_web/static/vendor/font-source/@'`
    dir=`dirname $target`
    if [ ! -d $dir ] ; then
        mkdir -p $dir
    fi
    cp $name $target
done
