#!/bin/sh
# Wrapper around yarn to update our javascript dependencies
set -e

cd scripts/yarn/

yarn install --check-files
yarn upgrade-interactive
yarn run build --scripts-prepend-node-path

# jQuery
cp node_modules/jquery/dist/jquery.min.js ../../weblate_web/static/jquery.min.js

# Clipboard
cp node_modules/clipboard/dist/clipboard.js ../../weblate_web/static/

# Source Sans/Code Pro fonts
mkdir -p ../../weblate_web/static/font-source
sed '/font-family/ a font-display: swap;' < node_modules/source-sans-pro/source-sans-pro.css > ../../weblate_web/static/font-source/source-sans-pro.css
sed '/font-family/ a font-display: swap;' < node_modules/source-code-pro/source-code-pro.css > ../../weblate_web/static/font-source/source-code-pro.css
find node_modules/source-sans-pro/ node_modules/source-code-pro/ -name SourceSansPro-ExtraLight.* -o  -name SourceSansPro-Light.* -o  -name SourceSansPro-Semibold.* -o -name SourceSansPro-Black.* -o -name SourceSansPro-Bold.* -o -name SourceSansPro-Regular.* -o -name SourceSansPro-It.* -o -name SourceSansPro-BoldIt.* -o -name SourceCodePro-Regular.* -o -name SourceCodePro-Bold.* | while read name ; do
    target=`echo $name | sed 's@node_modules/source-\(sans\|code\)-pro/@../../weblate_web/static/font-source/@'`
    dir=`dirname $target`
    if [ ! -d $dir ] ; then
        mkdir -p $dir
    fi
    cp $name $target
done

# Modernizr
mv modernizr.js ../../weblate_web/static/
