#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):
    replaces = [
        ("weblate_web", "0001_squashed_0030_service_note"),
        ("weblate_web", "0002_auto_20200316_1347"),
        ("weblate_web", "0003_auto_20200316_1536"),
        ("weblate_web", "0004_auto_20200318_0955"),
        ("weblate_web", "0005_package_limit_projects"),
        ("weblate_web", "0006_auto_20200320_0820"),
        ("weblate_web", "0007_service_hosted_billing"),
        ("weblate_web", "0008_service_limit_projects"),
        ("weblate_web", "0009_auto_20200422_2019"),
        ("weblate_web", "0010_auto_20200819_1135"),
        ("weblate_web", "0011_auto_20210313_0711"),
        ("weblate_web", "0012_project"),
        ("weblate_web", "0013_auto_20210313_0930"),
        ("weblate_web", "0014_auto_20210313_1037"),
        ("weblate_web", "0015_auto_20210313_1103"),
        ("weblate_web", "0016_index"),
        ("weblate_web", "0017_service_site_users"),
        ("weblate_web", "0018_service_site_projects"),
        ("weblate_web", "0019_auto_20210321_1547"),
        ("weblate_web", "0020_auto_20210322_1423"),
        ("weblate_web", "0021_auto_20210402_1659"),
        ("weblate_web", "0022_alter_project_options"),
        ("weblate_web", "0023_subscription_enabled"),
        ("weblate_web", "0024_package_limit_hosted_words_report_hosted_words_and_more"),
        ("weblate_web", "0025_alter_subscription_options"),
        (
            "weblate_web",
            "0026_package_limit_hosted_strings_report_hosted_strings_and_more",
        ),
        (
            "weblate_web",
            "0027_alter_donation_payment_alter_pastpayments_payment_and_more",
        ),
        ("weblate_web", "0028_subscription_package_link"),
        ("weblate_web", "0029_package_category"),
        ("weblate_web", "0030_donation_customer_service_customer"),
        ("weblate_web", "0031_fill_in_customer"),
        ("weblate_web", "0032_alter_donation_customer_alter_donation_user_and_more"),
        ("weblate_web", "0033_service_backup_box_service_backup_directory"),
        ("weblate_web", "0034_service_backup_size_service_backup_timestamp"),
        ("weblate_web", "0035_alter_service_backup_size"),
        ("weblate_web", "0036_remove_donation_user_remove_service_users_and_more"),
        ("weblate_web", "0037_package_hidden"),
        ("weblate_web", "0038_migrate_payments"),
        ("weblate_web", "0039_service_backup_subaccount"),
        ("weblate_web", "0040_service_backup_removed"),
        ("weblate_web", "0041_donation_new_payment_pastpayments_new_payment_and_more"),
        ("weblate_web", "0042_fill_in_uuid"),
        (
            "weblate_web",
            "0043_remove_donation_payment_remove_pastpayments_payment_and_more",
        ),
        ("weblate_web", "0044_rename_new_payment_donation_payment_and_more"),
        ("weblate_web", "0045_service_site_url_lock_alter_service_discoverable"),
        ("weblate_web", "0046_alter_service_site_url_lock"),
        ("weblate_web", "0047_replace_markupfield"),
        ("weblate_web", "0048_service_maintenance_window"),
        ("weblate_web", "0049_consolidate_donations"),
        ("weblate_web", "0050_subscription_payment_fk"),
        ("weblate_web", "0051_samlidentity_externalsyncstate"),
        ("weblate_web", "0052_discoveryactivation"),
    ]

    initial = True

    dependencies = [
        ("payments", "0001_squashed_0061_customerfollowup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSyncState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("cursor", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External sync state",
                "verbose_name_plural": "External sync states",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Article image, 1200x630 pixels", upload_to="images/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("verbose", models.CharField(max_length=400)),
                ("price", models.IntegerField()),
                ("limit_projects", models.IntegerField(default=0)),
                ("limit_languages", models.IntegerField(default=0)),
                ("limit_source_strings", models.IntegerField(default=0)),
                ("limit_hosted_words", models.IntegerField(default=0)),
                ("limit_hosted_strings", models.IntegerField(default=0)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (10, "Dedicated hosting"),
                            (20, "Shared hosting"),
                            (30, "Self-hosted support"),
                            (40, "Donation"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(blank=True, db_index=True, default=False),
                ),
            ],
            options={
                "verbose_name": "Service package",
                "verbose_name_plural": "Service packages",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("release", "Release"),
                            ("feature", "Features"),
                            ("announce", "Announcement"),
                            ("conferences", "Conferences"),
                            ("hosting", "Hosted Weblate"),
                            ("development", "Development"),
                            ("localization", "Localization"),
                        ],
                        db_index=True,
                        default="",
                        max_length=100,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "body_rendered",
                    models.TextField(
                        blank=True, db_column="_body_rendered", editable=False
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Will be generated from first body paragraph if empty",
                    ),
                ),
                (
                    "milestone",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=False,
                        help_text="Important milestone, shown in the milestones archive",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weblate_web.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        db_index=True,
                        default=weblate_web.models.generate_secret,
                        max_length=100,
                    ),
                ),
                (
                    "kind",
                    models.IntegerField(
                        choices=[(0, "Service"), (10, "Donation")], default=0
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community supported"),
                            ("hosted", "Dedicated hosted service"),
                            ("shared", "Hosted service"),
                            ("basic", "Basic self-hosted support"),
                            ("extended", "Extended self-hosted support"),
                            ("premium", "Premium self-hosted support"),
                        ],
                        default="community",
                        max_length=150,
                    ),
                ),
                (
                    "backup_repository",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("backup_box", models.IntegerField(default=0)),
                (
                    "backup_directory",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("backup_subaccount", models.IntegerField(default=0)),
                ("backup_size", models.BigIntegerField(default=0)),
                ("backup_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "backup_removed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("limit_languages", models.IntegerField(default=0)),
                ("limit_projects", models.IntegerField(default=0)),
                ("limit_source_strings", models.IntegerField(default=0)),
                ("limit_hosted_words", models.IntegerField(default=0)),
                ("limit_hosted_strings", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "maintenance_window",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Maintenance window"
                    ),
                ),
                ("hosted_billing", models.IntegerField(db_index=True, default=0)),
                ("discoverable", models.BooleanField(blank=True, default=False)),
                (
                    "site_url",
                    models.URLField(blank=True, default="", verbose_name="Server URL"),
                ),
                (
                    "site_url_lock",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Other URLs will get support status as out of limits. The URL needs to be updated manually in case it changes.",
                        verbose_name="Lock server URL",
                    ),
                ),
                ("site_title", models.TextField(default="Weblate")),
                ("site_version", models.TextField(blank=True, default="")),
                ("site_users", models.IntegerField(default=0)),
                ("site_projects", models.IntegerField(default=0)),
                (
                    "discover_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Server description"
                    ),
                ),
                (
                    "discover_image",
                    models.ImageField(
                        blank=True,
                        help_text="PNG or JPG image with a resolution of 570 x 260 pixels.",
                        upload_to="discover/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            weblate_web.models.validate_bitmap,
                        ],
                        verbose_name="Server image",
                    ),
                ),
                (
                    "donation_link_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Link text"
                    ),
                ),
                (
                    "donation_link_url",
                    models.URLField(blank=True, verbose_name="Link URL"),
                ),
                (
                    "donation_link_image",
                    models.ImageField(
                        blank=True, upload_to="donations/", verbose_name="Link image"
                    ),
                ),
                (
                    "donation_legacy_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer service",
                "verbose_name_plural": "Customer services",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField(default="")),
                ("site_title", models.TextField(default="")),
                ("version", models.TextField(default="")),
                ("ssh_key", models.TextField(default="")),
                ("users", models.IntegerField(default=0)),
                ("projects", models.IntegerField(default=0)),
                ("components", models.IntegerField(default=0)),
                ("languages", models.IntegerField(default=0)),
                ("source_strings", models.IntegerField(default=0)),
                ("hosted_strings", models.IntegerField(default=0)),
                ("hosted_words", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("discoverable", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weblate report",
                "verbose_name_plural": "Weblate reports",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=60)),
                ("url", models.CharField(max_length=120)),
                ("web", models.URLField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weblate project",
                "verbose_name_plural": "Weblate projects",
            },
        ),
        migrations.CreateModel(
            name="DiscoveryActivation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=weblate_web.models.generate_discovery_activation_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("state", models.CharField(max_length=400)),
                ("expires", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery activation",
                "verbose_name_plural": "Discovery activations",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                ("enabled", models.BooleanField(blank=True, default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weblate_web.package",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="payments.payment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer’s subscription",
                "verbose_name_plural": "Customer’s subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPastPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="payments.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past subscription payment",
                "verbose_name_plural": "Past subscription payments",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="past_payments",
            field=models.ManyToManyField(
                blank=True,
                related_name="past_subscription_set",
                through="weblate_web.SubscriptionPastPayment",
                to="payments.payment",
            ),
        ),
        migrations.CreateModel(
            name="SamlIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "raw_attrs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saml_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML identity",
                "verbose_name_plural": "SAML identities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="weblate_web_saml_identity_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("provider", "user"),
                        name="weblate_web_saml_identity_user_unique",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="subscriptionpastpayment",
            constraint=models.UniqueConstraint(
                fields=("subscription", "payment"),
                name="unique_subscription_past_payment",
            ),
        ),
    ]
