# Generated by Django 3.0.4 on 2020-03-13 12:24

import django.db.models.deletion
import markupfield.fields
from django.conf import settings
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):
    replaces = [
        ("weblate_web", "0001_initial"),
        ("weblate_web", "0002_image_post"),
        ("weblate_web", "0003_auto_20190509_0952"),
        ("weblate_web", "0004_auto_20190514_1457"),
        ("weblate_web", "0005_donation_link_image"),
        ("weblate_web", "0006_donation_reward_new"),
        ("weblate_web", "0007_auto_20190718_1614"),
        ("weblate_web", "0008_auto_20190718_1646"),
        ("weblate_web", "0009_auto_20190721_0935"),
        ("weblate_web", "0010_auto_20190726_0836"),
        ("weblate_web", "0011_auto_20190726_0837"),
        ("weblate_web", "0012_auto_20190807_1456"),
        ("weblate_web", "0013_subscription_active"),
        ("weblate_web", "0014_remove_subscription_price"),
        ("weblate_web", "0015_auto_20190807_1633"),
        ("weblate_web", "0016_auto_20190904_1320"),
        ("weblate_web", "0017_auto_20190904_1340"),
        ("weblate_web", "0018_auto_20190923_1626"),
        ("weblate_web", "0019_auto_20190923_1720"),
        ("weblate_web", "0020_auto_20190923_1713"),
        ("weblate_web", "0021_auto_20190923_1724"),
        ("weblate_web", "0022_auto_20190923_1725"),
        ("weblate_web", "0023_report_service"),
        ("weblate_web", "0024_auto_20190923_1726"),
        ("weblate_web", "0025_auto_20190923_1728"),
        ("weblate_web", "0026_auto_20190924_1501"),
        ("weblate_web", "0027_remove_package_backup"),
        ("weblate_web", "0028_auto_20191011_0927"),
        ("weblate_web", "0029_report_version"),
        ("weblate_web", "0030_service_note"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Article image, 1200x630 pixels", upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.UUIDField(blank=True, null=True)),
                (
                    "link_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Link text"
                    ),
                ),
                ("link_url", models.URLField(blank=True, verbose_name="Link URL")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                ("active", models.BooleanField(blank=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link_image",
                    models.ImageField(
                        blank=True, upload_to="donations/", verbose_name="Link image"
                    ),
                ),
                (
                    "reward",
                    models.IntegerField(
                        choices=[
                            (0, "No reward"),
                            (1, "Name in the list of supporters"),
                            (2, "Link in the list of supporters"),
                            (3, "Logo and link on the Weblate website"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        db_index=True,
                        default=weblate_web.models.generate_secret,
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community support"),
                            ("hosted", "Hosted service"),
                            ("basic", "Basic self-hosted support"),
                            ("extended", "Extended self-hosted support"),
                        ],
                        default="community",
                        max_length=150,
                    ),
                ),
                (
                    "backup_repository",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("limit_languages", models.IntegerField(default=0)),
                ("limit_source_strings", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("body", markupfield.fields.MarkupField(rendered_field=True)),
                (
                    "body_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                        ],
                        default="markdown",
                        max_length=30,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Will be generated from first body paragraph if empty",
                    ),
                ),
                ("_body_rendered", models.TextField(editable=False)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weblate_web.Image",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("release", "Release"),
                            ("feature", "Features"),
                            ("announce", "Announcement"),
                            ("conferences", "Conferences"),
                            ("hosting", "Hosted Weblate"),
                            ("development", "Development"),
                            ("localization", "Localization"),
                        ],
                        db_index=True,
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "milestone",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=False,
                        help_text="This is an important milestone, shown on milestones archive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.UUIDField(blank=True, null=True)),
                ("package", models.CharField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.Service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastPayments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.UUIDField()),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.Subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("verbose", models.CharField(max_length=400)),
                ("price", models.IntegerField()),
                ("limit_languages", models.IntegerField(default=0)),
                ("limit_source_strings", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField()),
                ("users", models.IntegerField()),
                ("projects", models.IntegerField()),
                ("components", models.IntegerField()),
                ("languages", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("site_title", models.TextField(default="")),
                ("ssh_key", models.TextField(default="")),
                ("source_strings", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.Service",
                    ),
                ),
                ("version", models.TextField(default="")),
            ],
        ),
    ]
