# Generated by Django 3.0.4 on 2020-03-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0002_auto_20200316_1347"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastpayments",
            name="donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weblate_web.Donation",
            ),
        ),
        migrations.AlterField(
            model_name="pastpayments",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weblate_web.Subscription",
            ),
        ),
    ]
