# Generated by Django 2.1.3 on 2019-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0002_image_post")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
