# Generated by Django 3.0.4 on 2020-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0003_auto_20200316_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("community", "Expired service"),
                    ("hosted", "Hosted service"),
                    ("basic", "Basic self-hosted support"),
                    ("extended", "Extended self-hosted support"),
                ],
                default="community",
                max_length=150,
            ),
        ),
    ]
