# -*- coding: utf-8 -*-
# Generated by Django 2.1.3 on 2019-07-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0004_auto_20190514_1457")]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="link_image",
            field=models.ImageField(
                blank=True, upload_to="donations/", verbose_name="Link image"
            ),
        )
    ]
