# Generated by Django 2.2.11 on 2020-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0004_auto_20200318_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="limit_projects",
            field=models.IntegerField(default=0),
        ),
    ]
