# Generated by Django 2.2.11 on 2020-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0005_package_limit_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("community", "Expired service"),
                    ("hosted", "Dedicated hosted service"),
                    ("shared", "Hosted service"),
                    ("basic", "Basic self-hosted support"),
                    ("extended", "Extended self-hosted support"),
                ],
                default="community",
                max_length=150,
            ),
        ),
    ]
