# Generated by Django 2.2.11 on 2020-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0006_auto_20200320_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hosted_billing",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
