# Generated by Django 2.2.11 on 2020-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0007_service_hosted_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="limit_projects",
            field=models.IntegerField(default=0),
        ),
    ]
