# Generated by Django 2.2.1 on 2019-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0008_auto_20190718_1646")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                help_text="Article image, 1200x630 pixels", upload_to="images/"
            ),
        )
    ]
