# Generated by Django 2.2.3 on 2019-07-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_web', '0009_auto_20190721_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='reward',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
