# Generated by Django 3.0.8 on 2020-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0009_auto_20200422_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("community", "Expired service"),
                    ("hosted", "Dedicated hosted service"),
                    ("shared", "Hosted service"),
                    ("basic", "Basic self-hosted support"),
                    ("extended", "Extended self-hosted support"),
                    ("premium", "Premium self-hosted support"),
                ],
                default="community",
                max_length=150,
            ),
        ),
    ]
