# Generated by Django 3.1.5 on 2021-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblate_web", "0010_auto_20200819_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="discoverable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="discoverable",
            field=models.BooleanField(default=False),
        ),
    ]
