# Generated by Django 2.2.3 on 2019-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0010_auto_20190726_0836")]

    operations = [
        migrations.RenameField(
            model_name="donation", old_name="reward_new", new_name="reward"
        )
    ]
