# Generated by Django 2.2.3 on 2019-08-07 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weblate_web", "0011_auto_20190726_0837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body_markup_type",
            field=models.CharField(
                choices=[
                    ("", "--"),
                    ("html", "HTML"),
                    ("plain", "Plain"),
                    ("markdown", "Markdown"),
                ],
                default="markdown",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community support"),
                            ("hosted", "Hosted service"),
                            ("basic", "Basic self-hosted support"),
                            ("extended", "Extended self-hosted support"),
                        ],
                        default="community",
                        max_length=150,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "secret",
                    models.CharField(
                        db_index=True,
                        default=weblate_web.models.generate_secret,
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField()),
                ("users", models.IntegerField()),
                ("projects", models.IntegerField()),
                ("components", models.IntegerField()),
                ("languages", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.Subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastPayments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.UUIDField()),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.Subscription",
                    ),
                ),
            ],
        ),
    ]
