# Generated by Django 3.1.7 on 2021-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblate_web", "0012_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="site_title",
            field=models.TextField(default="Weblate"),
        ),
        migrations.AddField(
            model_name="service",
            name="site_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="service",
            name="site_version",
            field=models.TextField(default=""),
        ),
    ]
