# Generated by Django 2.2.3 on 2019-08-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_web', '0013_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
    ]
