# Generated by Django 3.1.7 on 2021-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0013_auto_20210313_0930"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="discover_image",
            field=models.ImageField(
                blank=True, upload_to="discover/", verbose_name="Server image"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="discover_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Server description"
            ),
        ),
    ]
