# Generated by Django 3.1.7 on 2021-03-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblate_web", "0014_auto_20210313_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="discover_image",
            field=models.ImageField(
                blank=True,
                help_text="Please use 1200x630 pixels image for best rendering.",
                upload_to="discover/",
                verbose_name="Server image",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="site_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="service",
            name="site_version",
            field=models.TextField(blank=True, default=""),
        ),
    ]
