# Generated by Django 3.1.7 on 2021-03-13 13:15

from django.db import migrations


def create_index(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "mysql":
        schema_editor.execute(
            "CREATE FULLTEXT INDEX weblate_web_project_name_fulltext ON weblate_web_project(name)"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0015_auto_20210313_1103"),
    ]

    operations = [
        migrations.RunPython(code=create_index, atomic=False),
    ]
