# Generated by Django 3.1.7 on 2021-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0016_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="site_users",
            field=models.IntegerField(default=0),
        ),
    ]
