# Generated by Django 3.1.7 on 2021-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0017_service_site_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="site_projects",
            field=models.IntegerField(default=0),
        ),
    ]
