# -*- coding: utf-8 -*-
# Generated by Django 2.2.3 on 2019-09-23 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weblate_web", "0018_auto_20190923_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="source_strings",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        db_index=True,
                        default=weblate_web.models.generate_secret,
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("community", "Community support"),
                            ("hosted", "Hosted service"),
                            ("basic", "Basic self-hosted support"),
                            ("extended", "Extended self-hosted support"),
                        ],
                        default="community",
                        max_length=150,
                    ),
                ),
                ("backup_repository", models.CharField(default="", max_length=500)),
                ("limit_languages", models.IntegerField(default=0)),
                ("limit_source_strings", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weblate_web.Service",
            ),
        ),
    ]
