# Generated by Django 3.1.7 on 2021-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0019_auto_20210321_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="site_url",
            field=models.URLField(blank=True, default="", verbose_name="Server URL"),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("community", "Community supported"),
                    ("hosted", "Dedicated hosted service"),
                    ("shared", "Hosted service"),
                    ("basic", "Basic self-hosted support"),
                    ("extended", "Extended self-hosted support"),
                    ("premium", "Premium self-hosted support"),
                ],
                default="community",
                max_length=150,
            ),
        ),
    ]
