# -*- coding: utf-8 -*-
# Generated by Django 2.2.3 on 2019-09-23 15:13

from django.db import migrations

statuses = ("hosted", "basic", "extended")


def migrate_service(apps, schema_editor):
    Service = apps.get_model("weblate_web", "Service")
    Subscription = apps.get_model("weblate_web", "Subscription")
    for subscription in Subscription.objects.iterator():
        service = Service.objects.create(
            secret=subscription.secret,
            status=subscription.status
            if subscription.status in statuses
            else "community",
        )
        service.users.add(subscription.user)
        subscription.service = service
        subscription.save(update_fields=["service"])


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0019_auto_20190923_1720")]

    operations = [
        migrations.RunPython(migrate_service, migrations.RunPython.noop, elidable=True)
    ]
