# Generated by Django 2.2.3 on 2019-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0020_auto_20190923_1713")]

    operations = [
        migrations.RemoveField(model_name="subscription", name="secret"),
        migrations.RemoveField(model_name="subscription", name="user"),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("hosted", "Hosted service"),
                    ("basic", "Basic self-hosted support"),
                    ("extended", "Extended self-hosted support"),
                    ("install:linux", "Installation on your Linux server"),
                    ("install:docker", "Docker installation on your Linux server"),
                ],
                default="community",
                max_length=150,
            ),
        ),
    ]
