# Generated by Django 3.2.3 on 2021-05-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weblate_web", "0021_auto_20210402_1659"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "verbose_name": "Weblate project",
                "verbose_name_plural": "Weblate projects",
            },
        ),
    ]
