# Generated by Django 4.1.5 on 2023-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0023_subscription_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="limit_hosted_words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="hosted_words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="limit_hosted_words",
            field=models.IntegerField(default=0),
        ),
    ]
