# -*- coding: utf-8 -*-
# Generated by Django 2.2.3 on 2019-09-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0024_auto_20190923_1726")]

    operations = [
        migrations.RemoveField(model_name="report", name="subscription"),
        migrations.AlterField(
            model_name="report",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weblate_web.Service"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weblate_web.Service"
            ),
        ),
    ]
