# Generated by Django 4.2.6 on 2023-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0025_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="limit_hosted_strings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="hosted_strings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="limit_hosted_strings",
            field=models.IntegerField(default=0),
        ),
    ]
