# -*- coding: utf-8 -*-
# Generated by Django 2.2.5 on 2019-09-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0026_auto_20190924_1501")]

    operations = [migrations.RemoveField(model_name="package", name="backup")]
