# Generated by Django 5.0.6 on 2024-07-11 11:52

from django.db import migrations

import weblate_web.payments.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "weblate_web",
            "0026_package_limit_hosted_strings_report_hosted_strings_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="payment",
            field=weblate_web.payments.fields.Char32UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pastpayments",
            name="payment",
            field=weblate_web.payments.fields.Char32UUIDField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment",
            field=weblate_web.payments.fields.Char32UUIDField(blank=True, null=True),
        ),
    ]
