# -*- coding: utf-8 -*-
# Generated by Django 2.2.5 on 2019-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("weblate_web", "0027_remove_package_backup")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="backup_repository",
            field=models.CharField(blank=True, default="", max_length=500),
        )
    ]
