# Generated by Django 5.0.6 on 2024-10-11 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0030_donation_customer_service_customer"),
    ]

    operations = []
