# Generated by Django 5.1.3 on 2024-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0032_alter_donation_customer_alter_donation_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="backup_box",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="backup_directory",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
