# Generated by Django 5.1.3 on 2024-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0036_remove_donation_user_remove_service_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="hidden",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
