# Generated by Django 5.1.3 on 2024-12-18 11:45

from django.db import migrations


def migrate_payments(payments, customer) -> None:
    print(f"Moving {len(payments)} payments to {customer.name}")
    payments.update(customer=customer)


def update_payments(apps, schema_editor) -> None:
    Subscription = apps.get_model("weblate_web", "Subscription")
    Payment = apps.get_model("payments", "Payment")

    for subscription in Subscription.objects.prefetch_related("pastpayments_set"):
        payment_ids = {subscription.payment}
        payment_ids.update(past.payment for past in subscription.pastpayments_set.all())
        migrate_payments(
            Payment.objects.filter(pk__in=payment_ids), subscription.service.customer
        )


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0037_package_hidden"),
        ("payments", "0037_alter_customer_vat"),
    ]

    operations = [
        migrations.RunPython(update_payments, migrations.RunPython.noop, elidable=True),
    ]
