# Generated by Django 5.2.3 on 2025-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0038_migrate_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="backup_subaccount",
            field=models.IntegerField(default=0),
        ),
    ]
