# Generated by Django 5.2.3 on 2025-07-11 14:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0039_service_backup_subaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="backup_removed",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
