# Generated by Django 5.2.4 on 2025-07-28 09:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0040_service_backup_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="new_payment",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pastpayments",
            name="new_payment",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="subscription",
            name="new_payment",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
