# Generated by Django 5.2.4 on 2025-07-28 09:20

from django.db import migrations

from weblate_web.payments.fields import migrate_uuid_field


def migrate(apps, schema_editor) -> None:
    migrate_uuid_field(
        apps.get_model("weblate_web", "Donation"), "payment", "new_payment"
    )
    migrate_uuid_field(
        apps.get_model("weblate_web", "Subscription"), "payment", "new_payment"
    )
    migrate_uuid_field(
        apps.get_model("weblate_web", "PastPayments"), "payment", "new_payment"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0041_donation_new_payment_pastpayments_new_payment_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True),
    ]
