# Generated by Django 5.2.4 on 2025-07-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0042_fill_in_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="pastpayments",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payment",
        ),
        migrations.AlterField(
            model_name="pastpayments",
            name="new_payment",
            field=models.UUIDField(),
        ),
    ]
