# Generated by Django 5.2.4 on 2025-07-28 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "weblate_web",
            "0043_remove_donation_payment_remove_pastpayments_payment_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="new_payment",
            new_name="payment",
        ),
        migrations.RenameField(
            model_name="pastpayments",
            old_name="new_payment",
            new_name="payment",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="new_payment",
            new_name="payment",
        ),
    ]
