# Generated by Django 5.2.4 on 2025-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0044_rename_new_payment_donation_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="site_url_lock",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Lock server URL"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="discoverable",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
