# Generated by Django 5.2.4 on 2025-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0045_service_site_url_lock_alter_service_discoverable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="site_url_lock",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Other URLs will get support status as out of limits. The URL needs to be updated manually in case it changes.",
                verbose_name="Lock server URL",
            ),
        ),
    ]
