#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.15 on 2026-07-08 16:30

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0051_samlidentity_externalsyncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryActivation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=weblate_web.models.generate_discovery_activation_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("state", models.CharField(max_length=400)),
                ("callback_url", models.URLField(max_length=500)),
                ("expires", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery activation",
                "verbose_name_plural": "Discovery activations",
            },
        ),
    ]
