# Generated by Django 5.2.15 on 2026-07-08 16:30

import django.db.models.deletion
from django.db import migrations, models

import weblate_web.models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_web", "0051_samlidentity_externalsyncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryActivation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=weblate_web.models.generate_discovery_activation_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("state", models.CharField(max_length=400)),
                ("callback_url", models.URLField(max_length=500)),
                ("expires", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weblate_web.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery activation",
                "verbose_name_plural": "Discovery activations",
            },
        ),
    ]
