#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import datetime
import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("invoices", "0001_initial"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, unique=True)),
                (
                    "percents",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.IntegerField(editable=False)),
                (
                    "number",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    "kind", models.CharField()
                                ),
                                2,
                                models.Value("0"),
                            ),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.functions.datetime.Extract(
                                        "issue_date", "year"
                                    ),
                                    "%%",
                                    models.Value(2000),
                                ),
                                models.CharField(),
                            ),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    "sequence", models.CharField()
                                ),
                                6,
                                models.Value("0"),
                            ),
                        ),
                        help_text="Invoice number is automatically generated",
                        output_field=models.CharField(max_length=20),
                        unique=True,
                    ),
                ),
                ("issue_date", models.DateField(default=datetime.date.today)),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date / Quote validity, keep blank unless specific terms are needed",
                    ),
                ),
                (
                    "tax_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of taxable supply, keep blank for issue date",
                    ),
                ),
                (
                    "kind",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (10, "Invoice"),
                            (50, "Pro Forma Invoice"),
                            (90, "Quote"),
                        ]
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Hosting"),
                            (2, "Support"),
                            (3, "Development / Consultations"),
                            (4, "Donation"),
                        ],
                        help_text="Helps to categorize income",
                    ),
                ),
                (
                    "customer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Text will be shown on the generated invoice",
                        max_length=100,
                    ),
                ),
                (
                    "customer_note",
                    models.TextField(
                        blank=True,
                        help_text="Text will be shown on the generated invoice",
                    ),
                ),
                (
                    "quote_status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (10, "Lost"),
                            (20, "Superseded"),
                            (30, "Accepted elsewhere"),
                            (40, "Archived"),
                        ],
                        default=0,
                        help_text="CRM status for quote follow-up.",
                        verbose_name="Quote status",
                    ),
                ),
                (
                    "quote_status_note",
                    models.TextField(
                        blank=True,
                        help_text="Internal note explaining why the quote was closed.",
                        verbose_name="Quote status note",
                    ),
                ),
                (
                    "vat_rate",
                    models.IntegerField(
                        default=0,
                        help_text="VAT rate in percents to apply on the invoice",
                        verbose_name="VAT rate",
                    ),
                ),
                (
                    "currency",
                    models.IntegerField(
                        choices=[(0, "EUR"), (1, "CZK"), (2, "USD"), (3, "GBP")],
                        default=0,
                    ),
                ),
                (
                    "prepaid",
                    models.BooleanField(
                        default=False,
                        help_text="Invoices paid in advance (card payment, invoices issued after paying pro forma)",
                        verbose_name="Already paid",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "permissions": [("view_income", "Can view income tracking")],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "quantity_unit",
                    models.IntegerField(choices=[(0, ""), (1, "hours")], default=0),
                ),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
