#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Generated by Django 5.2.17 on 2026-08-06 11:13

from __future__ import annotations

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("invoices", "0002_alter_invoice_customer_alter_invoice_discount_and_more"),
        ("invoices", "0003_alter_invoice_kind"),
        ("invoices", "0004_invoice_number"),
        ("invoices", "0005_alter_invoice_currency_alter_invoice_number"),
        ("invoices", "0006_remove_invoice_number_alter_invoice_kind"),
        ("invoices", "0007_invoice_number"),
        ("invoices", "0008_invoice_category"),
        ("invoices", "0009_alter_invoice_kind"),
        ("invoices", "0010_remove_invoiceitem_invoice_delete_invoice_and_more"),
        ("invoices", "0011_invoice_invoiceitem_invoice_unique_number"),
        ("invoices", "0012_invoiceitem_package_alter_invoiceitem_description_and_more"),
        ("invoices", "0013_invoice_extra"),
        ("invoices", "0014_alter_invoice_currency"),
        ("invoices", "0015_invoiceitem_end_date_invoiceitem_start_date"),
        ("invoices", "0016_alter_invoice_category_and_more"),
        ("invoices", "0017_alter_invoiceitem_package"),
        ("invoices", "0018_alter_invoice_options"),
        ("invoices", "0019_alter_invoice_category"),
        ("invoices", "0020_invoice_customer_note"),
        ("invoices", "0021_invoice_tax_date"),
        ("invoices", "0022_set_tax_date"),
        ("invoices", "0023_alter_invoice_tax_date"),
        ("invoices", "0024_alter_invoice_options"),
        ("invoices", "0025_invoice_quote_status"),
    ]

    initial = True

    dependencies = [
        ("invoices", "0001_squashed_0025_invoice_quote_status"),
        ("payments", "0001_squashed_0061_customerfollowup"),
        ("weblate_web", "0001_squashed_0052_discoveryactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.customer"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                help_text="Automatically applied to all invoice items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.discount",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Invoices tracking, use for issuing invoice from quote",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
                verbose_name="Parent invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoices.invoice"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecting package will automatically fill in description and price",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="weblate_web.package",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                models.F("sequence"),
                django.db.models.functions.datetime.Extract("issue_date", "year"),
                models.F("kind"),
                name="unique_number",
            ),
        ),
    ]
