# Generated by Django 5.1.2 on 2024-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_customer_alter_invoice_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (10, "Invoice"),
                    (20, "Proforma"),
                    (30, "Quote"),
                    (40, "Draft"),
                ]
            ),
        ),
    ]
