#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from __future__ import annotations

# Generated by Django 5.2.17 on 2026-09-16 14:33
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoice_calculation_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date"],
                "permissions": [
                    ("view_income", "Can view income tracking"),
                    (
                        "manage_invoice_corrections",
                        "Can manage invoice corrections and refunds",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_net",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_note",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_reason",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_rounding",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_token",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_vat",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="credited_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_corrections",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="fully_credited",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uncollectible",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uncollectible_note",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
