# Generated by Django 5.1.2 on 2024-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_invoice_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (10, "Invoice"),
                    (50, "Pro Forma Invoice"),
                    (90, "Quote"),
                ]
            ),
        ),
    ]
