# Generated by Django 5.1.2 on 2024-10-24 06:32

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_remove_invoiceitem_invoice_delete_invoice_and_more"),
        ("payments", "0034_remove_payment_draft_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.IntegerField(editable=False)),
                (
                    "number",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    "kind", models.CharField()
                                ),
                                2,
                                models.Value("0"),
                            ),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.functions.datetime.Extract(
                                        "issue_date", "year"
                                    ),
                                    "%%",
                                    models.Value(2000),
                                ),
                                models.CharField(),
                            ),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    "sequence", models.CharField()
                                ),
                                6,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(max_length=20),
                        unique=True,
                    ),
                ),
                ("issue_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField(blank=True)),
                (
                    "kind",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (10, "Invoice"),
                            (50, "Pro Forma Invoice"),
                            (90, "Quote"),
                        ]
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Hosting"),
                            (2, "Support"),
                            (3, "Development"),
                            (4, "Donation"),
                        ],
                        default=1,
                    ),
                ),
                ("customer_reference", models.CharField(blank=True, max_length=100)),
                ("vat_rate", models.IntegerField(default=0)),
                (
                    "currency",
                    models.IntegerField(choices=[(0, "EUR"), (1, "CZK")], default=0),
                ),
                (
                    "prepaid",
                    models.BooleanField(
                        default=False,
                        help_text="Invoices paid in advance (card payment, pro forma)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.customer",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="invoices.discount",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "quantity_unit",
                    models.IntegerField(choices=[(0, ""), (1, "hours")], default=0),
                ),
                ("unit_price", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                models.F("sequence"),
                django.db.models.functions.datetime.Extract("issue_date", "year"),
                models.F("kind"),
                name="unique_number",
            ),
        ),
    ]
