# Generated by Django 5.1.2 on 2024-10-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_invoice_invoiceitem_invoice_unique_number"),
        ("weblate_web", "0032_alter_donation_customer_alter_donation_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="weblate_web.package",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
    ]
