# Generated by Django 5.1.2 on 2024-10-24 07:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0012_invoiceitem_package_alter_invoiceitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
