# Generated by Django 5.1.2 on 2024-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0013_invoice_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.IntegerField(
                choices=[(0, "EUR"), (1, "CZK"), (2, "USD"), (3, "GBP")], default=0
            ),
        ),
    ]
