# Generated by Django 5.1.2 on 2024-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0014_alter_invoice_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
