# Generated by Django 5.1.3 on 2024-11-19 08:58

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0015_invoiceitem_end_date_invoiceitem_start_date"),
        ("weblate_web", "0032_alter_donation_customer_alter_donation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Hosting"),
                    (2, "Support"),
                    (3, "Development"),
                    (4, "Donation"),
                ],
                help_text="Helps to categorize income",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer_reference",
            field=models.CharField(
                blank=True,
                help_text="Text will be shown on the generated invoice",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                help_text="Automatically applied to all invoice items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.discount",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Due date / Quote validity, keep blank unless specific terms are needed",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            "kind", models.CharField()
                        ),
                        2,
                        models.Value("0"),
                    ),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Extract(
                                "issue_date", "year"
                            ),
                            "%%",
                            models.Value(2000),
                        ),
                        models.CharField(),
                    ),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            "sequence", models.CharField()
                        ),
                        6,
                        models.Value("0"),
                    ),
                ),
                help_text="Invoice number is automatically generated",
                output_field=models.CharField(max_length=20),
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Invoices tracking, use for issuing invoice from quote",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
                verbose_name="Parent invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="prepaid",
            field=models.BooleanField(
                default=False,
                help_text="Invoices paid in advance (card payment, invoices issued after paying pro forma)",
                verbose_name="Already paid",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_rate",
            field=models.IntegerField(
                default=0,
                help_text="VAT rate in percents to apply on the invoice",
                verbose_name="VAT rate",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecting package will automatically fill in description and price",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="weblate_web.package",
            ),
        ),
    ]
