# Generated by Django 5.1.3 on 2024-12-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0016_alter_invoice_category_and_more"),
        ("weblate_web", "0037_package_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecting package will automatically fill in description and price",
                limit_choices_to={"hidden": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="weblate_web.package",
            ),
        ),
    ]
