# Generated by Django 5.2.1 on 2025-05-27 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0017_alter_invoiceitem_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-issue_date"]},
        ),
    ]
