# Generated by Django 5.2.3 on 2025-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0018_alter_invoice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Hosting"),
                    (2, "Support"),
                    (3, "Development / Consultations"),
                    (4, "Donation"),
                ],
                help_text="Helps to categorize income",
            ),
        ),
    ]
