# Generated by Django 5.2.4 on 2025-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0019_alter_invoice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer_note",
            field=models.TextField(
                blank=True, help_text="Text will be shown on the generated invoice"
            ),
        ),
    ]
