# Generated by Django 5.2.8 on 2025-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0020_invoice_customer_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_date",
            field=models.DateField(
                blank=True,
                help_text="Date of taxable supply, keep blank for issue date",
                null=True,
            ),
        ),
    ]
