# Generated by Django 5.2.8 on 2025-12-10 14:45

from django.db import migrations
from django.db.models import F


def migrate(apps, schema_editor) -> None:
    Invoice = apps.get_model("invoices", "Invoice")
    Invoice.objects.filter(tax_date=None).update(tax_date=F("issue_date"))


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0021_invoice_tax_date"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop, elidable=True),
    ]
