# Generated by Django 5.2.9 on 2025-12-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_alter_invoice_tax_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date'], 'permissions': [('view_income', 'Can view income tracking')]},
        ),
    ]
