# Generated by Django 5.2.15 on 2026-07-07

import django.utils.translation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0024_alter_invoice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="quote_status",
            field=models.IntegerField(
                choices=[
                    (0, django.utils.translation.pgettext_lazy("Quote status", "Open")),
                    (
                        10,
                        django.utils.translation.pgettext_lazy("Quote status", "Lost"),
                    ),
                    (
                        20,
                        django.utils.translation.pgettext_lazy(
                            "Quote status", "Superseded"
                        ),
                    ),
                    (
                        30,
                        django.utils.translation.pgettext_lazy(
                            "Quote status", "Accepted elsewhere"
                        ),
                    ),
                    (
                        40,
                        django.utils.translation.pgettext_lazy(
                            "Quote status", "Archived"
                        ),
                    ),
                ],
                default=0,
                help_text="CRM status for quote follow-up.",
                verbose_name="Quote status",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="quote_status_note",
            field=models.TextField(
                blank=True,
                help_text="Internal note explaining why the quote was closed.",
                verbose_name="Quote status note",
            ),
        ),
    ]
