# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlhosted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
