# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wlhosted', '0002_auto_20181023_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='instance',
        ),
        migrations.AddField(
            model_name='customer',
            name='origin',
            field=models.URLField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='repeat',
            field=weblate.utils.fields.JSONField(default='', editable=False),
            preserve_default=False,
        ),
    ]
