# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-24 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlhosted', '0003_auto_20181023_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
