# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wlhosted', '0004_customer_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoice',
        ),
        migrations.AddField(
            model_name='payment',
            name='extra',
            field=weblate.utils.fields.JSONField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
