# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlhosted', '0005_auto_20181024_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
