name: Test

on:
  push:
  pull_request:

jobs:
  test:
    services:
      postgres:
        image: postgres:18.4-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: weblate
          POSTGRES_DB: weblate
      mariadb:
        image: mariadb:10.11.18@sha256:de61fed4a40d3842f3ee09944ba52792156cfd9adf489b2cc670fc6ded28df8d
        env:
          MARIADB_ROOT_PASSWORD: weblate
          MARIADB_DATABASE: weblate
        ports:
        - 3306:3306
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.11'
        - '3.12'
        - '3.13'
        database:
        - sqlite
        - mariadb
        - postgresql
    name: Python ${{ matrix.python-version }}, ${{ matrix.database }}
    env:
      CI_DATABASE: ${{ matrix.database }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: Install apt dependencies
      # gettext is needed as Django uses msgfmt to compile MO files
      run: |
        sudo apt update
        sudo apt install gettext
    - name: Start validation service
      env:
        # renovate: datasource=github-releases depName=gflohr/e-invoice-eu-validator versioning=loose
        VALIDATOR_VERSION: 2.16.4
      run: |
        curl -L "https://github.com/gflohr/e-invoice-eu-validator/releases/download/v$VALIDATOR_VERSION/validator-$VALIDATOR_VERSION-jar-with-dependencies.jar" > /tmp/validator.jar
        PORT=7070 java -jar /tmp/validator.jar > /tmp/validator.log 2>&1 &
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        cache-suffix: test
        version: 0.12.3
    - name: Install Python dependencies
      run: uv sync --dev
    - name: Compile MO files
      run: uv run --no-sync ./scripts/generate-locales
    - name: Collect static files
      run: uv run --no-sync ./manage.py collectstatic
    - name: Django checks
      run: uv run --no-sync ./manage.py check
    - name: Test with Django
      env:
        EINVOICE_VALIDATOR_URL: http://localhost:7070/
      run: uv run --no-sync pytest --junitxml=junit.xml weblate_web
    - name: Coverage
      run: uv run --no-sync coverage xml
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} # zizmor: ignore[secrets-outside-env]
        flags: unittests
        name: Python ${{ matrix.python-version }}
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # zizmor: ignore[secrets-outside-env]
    - name: Show validation logs
      if: ${{ !cancelled() }}
      run: cat /tmp/validator.log
permissions:
  contents: read
